In [1]:
import pandas as pd
from c import file_names, main_columns, ped_columns, decode_key

In [3]:
# read csv
data = {}
for file_name in file_names:
    data[file_name] = pd.read_csv(f'data/2018/{file_name}', encoding='iso-8859-2', names=main_columns, sep=';', low_memory=False)
    data[file_name].dropna(axis='columns', how='all', inplace=True)
    data[file_name]['Kraj'] = file_names[file_name]

chodci = pd.read_csv(f'data/2018/CHODCI.csv', encoding='iso-8859-2', names=ped_columns, sep=';', low_memory=False)
chodci

,identifikacni_cislo,kategorie_chodce,stav_chodce,chovani_chodce,situace_v_miste_nehody
0,2100180003,2,9,3,0
1,2100180007,2,1,1,4
2,2100180039,1,9,3,0
3,2100180047,1,2,3,0
4,2100180051,2,1,1,4
...,...,...,...,...,...
3727,190906180773,2,1,1,4
3728,190906180786,3,1,5,10
3729,190906180815,3,1,1,4
3730,190906180817,2,1,0,0
3731,190906180827,1,0,3,10

In [6]:
# make it one table and save
clean = pd.concat( data, sort = False )
clean.to_csv('clean-2018.csv')
clean

             identifikacni_cislo  druh_pozemni_komunikace  \
00.csv 0              2100180001                        6
       1              2100180002                        5
       2              2100180003                        8
       3              2100180004                        5
       4              2100180005                        6
...                          ...                      ...
19.csv 2972         190906180826                        6
       2973         190906180827                        2
       2974         190906180828                        2
       2975         190906180829                        6
       2976         190906180830                        0

             cislo_pozemni_komunikace den_mesic_rok  weekday(p2a)   cas  \
00.csv 0                          NaN    2018-01-01             1  2356
       1                          NaN    2018-01-01             1    50
       2                          NaN    2018-01-01             1    40
       3                          NaN    2018-01-01             1   114
       4                          NaN    2018-01-01             1   232
...                               ...           ...           ...   ...
19.csv 2972                       NaN    2018-12-28             5  2560
       2973                     222.0    2018-12-30             0  2045
       2974                     210.0    2018-12-30             0  2200
       2975                       NaN    2018-12-31             1  1713
       2976                       6.0    2018-12-31             1  2312

             druh_nehody  druh_srazky_jedoucich_vozidel  druh_pevne_prekazky  \
00.csv 0               1                              4                    0
       1               3                              0                    2
       2               4                              0                    0
       3               1                              4                    0
       4               3                              0                    4
...                  ...                            ...                  ...
19.csv 2972            2                              0                    0
       2973            4                              0                    0
       2974            3                              0                    4
       2975            3                              0                    9
       2976            3                              0                    4

             charakter_nehody  ...    l        n                       p  \
00.csv 0                    2  ...  NaN      NaN                     NaN
       1                    2  ...  NaN      NaN                     NaN
       2                    1  ...  NaN      NaN                     NaN
       3                    2  ...  NaN      NaN                     NaN
       4                    1  ...  NaN      NaN                     NaN
...                       ...  ...  ...      ...                     ...
19.csv 2972                 2  ...  NaN  2611685      Opačnýkesměruúseku
       2973                 1  ...  222   184688  Souhlasnýsesměremúseku
       2974                 2  ...  210  3562022      Opačnýkesměruúseku
       2975                 2  ...  NaN   183504  Souhlasnýsesměremúseku
       2976                 2  ...   D6  3513942  Souhlasnýsesměremúseku

                  q         r          s                   t  lokalita_nehody  \
00.csv 0        NaN       NaN        NaN                 NaN                1
       1        NaN       NaN        NaN                 NaN                1
       2        NaN       NaN        NaN                 NaN                1
       3        NaN       NaN        NaN                 NaN                1
       4        NaN       NaN        NaN                 NaN                1
...             ...       ...        ...                 ...              ...
19.csv 2972  Pomalý  560570.0   552844.0  GN_V0.1UIR-ADR_410                1
       2973  Pomalý  560383.0   550451.0  GN_V0.1UIR-ADR_410                1
       2974  Pomalý  560286.0        NaN  GN_V0.1UIR-ADR_410                2
       2975  Pomalý  560383.0  1494945.0  GN_V0.1UIR-ADR_410                1
       2976  Pomalý  560570.0        NaN  GN_V0.1UIR-ADR_410                2

                                            Kraj    o
00.csv 0            nehody na území hl. m. Prahy  NaN
       1            nehody na území hl. m. Prahy  NaN
       2            nehody na území hl. m. Prahy  NaN
       3            nehody na území hl. m. Prahy  NaN
       4            nehody na území hl. m. Prahy  NaN
...                                          ...  ...
19.csv 2972  nehody na území Karlovarského kraje  NaN
       2973  nehody na území Karlovarského kraje  NaN
       2974  nehody na území Karlovarského kraje  NaN
       2975  nehody na území Karlovarského kraje  NaN
       2976  nehody na území Karlovarského kraje  NaN

[104764 rows x 64 columns]

### Kolik nehod v roce 2018 PČR zaznamenala?

In [5]:
len(clean.index)

104764

### Kolik procent zaznamenaných nehod bylo smrtelných?

In [34]:
deadly = clean[clean['usmrceno_osob'] > 0]['usmrceno_osob']
len(deadly)

509

### Kolik lidí zemřelo při srážce s odrazníkem, patníkem, sloupkem dopravní značky apod.?

In [38]:
solid_object = clean[(clean['druh_pevne_prekazky'] == 3) & deadly] #(clean['usmrceno_osob'] > 0)]['usmrceno_osob']
solid_object['usmrceno_osob'].sum()

4

### Kolik procent zaznamenaných nehod, které se staly na kolejích tramvaje, bylo smrtelných?

In [45]:
# situovani_nehody_na_komunikaci == 7
on_tram_trails = clean[clean['situovani_nehody_na_komunikaci'] == 7]
deadly_on_tram_trails = clean[(clean['situovani_nehody_na_komunikaci'] == 7) & deadly]
(len(deadly_on_tram_trails) / len(on_tram_trails)) * 100

0.8771929824561403

### Vyberte časté výrobní značky vozidel (např. Škoda, BMW): ty které se účastnily alespoň padesáti nehod. Vykreslete graf, který pro každou častou výrobní značku ukáže procento nehod v zatáčce (vzhledem k celkovému počtu nehod vozidel této značky).
### Například: vozidla značky ŠKODA se účastnila 21421 nehod, z toho 2505 nehod bylo v zatáčce. 2505 z 21421 je 11,7%, graf tedy bude pro značku ŠKODA ukazovat 11,7%.

### Záznamy jako žádná z uvedených můžete pro jednoduchost považovat za samostatné značky.